### ISSUE TITLE
wsd-get-json: (wrong-type-argument number-or-marker-p nil)

### ISSUE THREAD

**Issue by DinoChiesa** [josteink/wsd-mode#16]
when I use test.wsd and C-c C-c, I get an exception in wsd-get-json: 
 (wrong-type-argument number-or-marker-p nil)

It appears to be in the call to (left-char), which on my emacs references a variable that may not be defined. If I replace the call in wsd-get-json to (left-char) with (backward-char) then all works well.

**Comment by josteink** [comment]
Thanks for the report!

Might be version-related. I'll do some testing and create a fix.

If I may ask: what version of Emacs are you running?

**Comment by DinoChiesa** [comment]
GNU Emacs 24.3.1 (x86_64-apple-darwin, NS apple-appkit-1038.36)
 of 2013-03-12 on bob.porkrind.org

**Comment by josteink** [comment]
Ah. Older than any machine I run on.

Will add more info version compatibility to the changelist before next stable release. Thanks for the help!
