### ISSUE TITLE
Incorrect indentation when "state" is used inside of "alt"

### ISSUE THREAD

**Issue by dlasko** [josteink/wsd-mode#24]
This is my first github issue submission, so please excuse any noob mistakes (insufficient information, poor etiquette, etc.).

First, thanks for wsd mode!  Very handy.  I installed it on GNU Emacs 24.4.1 running on Windows 7.

It seems there is a problem with indentation when "state" is used within "alt".  Here is an example wsd, indented how I believe it should be:

----------------------
```
title Sandwich Request

participant Darren as D
participant Kim as K

D->K: Make me a sandwich!

alt Kim in good mood
    state over K, K
    Kim makes a sandwich
    end state

    K-->D: Here's your yummy sandwich!
else Kim in bad mood
    state over K, K
    Kim glares at Darren
    end state

    K-->D: Make your own damn sandwich!
end
```
----------------------

However, this is not how it is indented if you type it (the first "end state" is incorrectly indented, along with everything after it), and you actually get a message of "Wrong type argument: wholenump, -4" when you hit the enter key after typing the "else" line.  You get the same error if you select all lines in the buffer and perform "M-x indent-region".

Thanks!
Darren

**Comment by josteink** [comment]
Hi there.

`state` seems to be a keyword I didn't know about, so it's not treated in any special way indentation-wise. `end` is though and will cancel the indentation for `alt`.

I'll add support for `state` and hopefully everything will sort itself out.

It's probably a quick fix, but i prefer to test things properly and I'm on Christmas holiday with the family, so expect it to take a few days before you see anything.

**Comment by josteink** [comment]
Have a Christmas present :)

**Comment by dlasko** [comment]
Hello again!  And thank you for the Christmas present! :)

That seemed to fix the issue for "state", and my simple test case.  However, it seems that maybe the "note" keyword has the same issue, at least when doing a multi-line note with "end note" used for termination.  You can see this behavior by replacing all instances of "state" with "note" in the original post's example.  It's highlighting "note over", so it must be recognizing the keyword, but it's not handling the indentation properly.

I don't see a way to "re-open" this issue... should I create a new issue for this, or do you just want to track it using this issue number?

Thanks again,
Darren

**Comment by josteink** [comment]
See my reply on your other issue: https://github.com/josteink/wsd-mode/issues/25#issuecomment-167629558

I suggest we keep this one closed for now.
