### ISSUE TITLE
Various pro-only features not supported

### ISSUE THREAD

**Issue by dlasko** [josteink/wsd-mode#25]
Hello again,

It looks like the "parallel" keyword is not recognized, and it's not indenting the stuff inside of the parallel's curly braces.

Here is a link that explains "parallel" (and probably all other keywords): https://www.websequencediagrams.com/examples.html

Thanks,
Darren

**Comment by josteink** [comment]
Hey again. Thanks for the bug report!

It seems most of the missing keywords and syntax
are pro-only features, which explains why I really aren't that familiar with them.

Some may be simple to implement, while others will be harder.

Right now I think the single most complex feature is going to be keywords which may or may not lead to indentation. I don't have any code top support such duality.

I'll look deeper into this, and try to create separate  issues for things I think can be solved separately.

I'll link them back in here, and that way you can keep track of what's supposed to work or not. Can't promise any timelines though.

Sounds good?

**Comment by dlasko** [comment]
OK, sounds good.

One other thing I just noticed is that "state" (just like "note") supports both a single-line version and a multi-line version.  It looks like the code you added for supporting "state" only considers the multi-line case, so if you use the single-line version, it incorrectly indents the next line (this is the "keywords that may or may not lead to indentation" issue you mentioned... just wanted to make sure you were aware that both "note" and "state" fall into this category).

Thanks again for this mode!

Happy New Year,
Darren

**Comment by josteink** [comment]
Issue created for optional single/multi-line statements:

https://github.com/josteink/wsd-mode/issues/26

**Comment by josteink** [comment]
Issues created:

* [Keywords with single/multi-line statements](https://github.com/josteink/wsd-mode/issues/26): Solution drafted. NOT completed.
* [Parallel keyword not supported](https://github.com/josteink/wsd-mode/issues/27): Solution aligned with single/multi-line statements.
* [Ref keyword not supported](https://github.com/josteink/wsd-mode/issues/28): Postponed until other issues have been resolved.
* [Autonumbering keyword not supported](https://github.com/josteink/wsd-mode/issues/29): Solution draften. Not implemented.
* [Footer keyword not supported](https://github.com/josteink/wsd-mode/issues/30): Solution drafted. No implemented.
* [Extended text descriptions not supported](https://github.com/josteink/wsd-mode/issues/31): Surprisingly complex feature. Solution not drafted. Postponed and not prioritized at all.

Unless I am mistaken, there should now be discrete issues for every *syntax* supported by the websequencediagrams website for sequence diagram scripts, and this issue can be closed.

There are still other features the site supports which the mode doesn't (loading and saving files, etc). If support for those features are deemed interesting for this major-mode, then please create issues for them.

**Comment by josteink** [comment]
All major issues which I intend to fix in this round has now been completed.

If there's still anything considered crucial shortcomings, feel free to request them in their own issues.
