### ISSUE TITLE
Support keywords with optional end-blocks

### ISSUE THREAD

**Issue by josteink** [josteink/wsd-mode#26]
As seen in [the documentation](https://www.websequencediagrams.com/examples.html), the keywords `note` and `state` can be used as single line statements of the following format

````
state over Server: LISTEN
````

Or as multi-line statements in the following format:

````
state over K, K
Kim makes a sandwich
end state
````

The current implementation for `note` supports only the former and `state` supports only the latter. They should ideally both support both,

The current implementation for `state` makes it a indentation-causing keyword. Supporting this at the same time as we want to support the single-line version will require that a stateful parser (instead of the currently 100% stateless, functional one) be implemented: to know if `state` should cause indentation or not, we must await future input to see if it contains `end state`.

No matter how that is done, it's going to get ugly. At least a lot uglier and more complex than the code which we have right now.

A way to avoid this problem is looking at it differently: Instead of optional indentation, consider it optional end-statements. That way the keyword should *not* cause indentation, but instead make the various `end`-keyword variations (`end note`, `end state`) *not* cause un-indentation.

That will be much simpler to implement, and won't require the parser to keep state, while keeping the overall indentation of the documents correct.

Fixing this should involve some reasonably simple changes to the following code-segments: https://github.com/josteink/wsd-mode/blob/master/wsd-mode.el#L124-L126

CC: @dlasko

**Comment by dlasko** [comment]
Hi Jostein,

Perhaps another approach which could allow indentation but still keep your parser stateless (I think?) would be to key off of the presence of a colon in the state/note line.  If there's a colon, then it's the single-line (non-indentation-causing) variant; if there's not a colon, then it's the multi-line (indentation-causing) variant.  I haven't really looked at your code (and my lisp skills suck anyway), so not sure how difficult/easy it would be to use this approach.

Thanks,
Darren

**Comment by josteink** [comment]
Yeah. After posting that, I noticed/realized the same.

Right now I just analyze the *first token* of a line (and nothing more) to determine if it should be indented or not. I will just need to extend that logic to match the whole line against a set of regular expressions instead, and that can be used to check for the colon.

I will need to do this anyway to support the construct with `parallell {` anyway, so I'll probably go down this line. The changes should be equally manageable, and like you said, 100% stateless.

Thanks for your input.

**Comment by josteink** [comment]
Preliminary work on this in being conducted in the [indentation branch](https://github.com/josteink/wsd-mode/tree/indentation) (which is currently incomplete, and not working).

**Comment by josteink** [comment]
The indentation-branch is not complete yet, but the it's getting closer. Right now I think what's there should work, but I cannot guarantee I got everything 100% right.

@dlasko : Would you mind checking it out, and see if you see any obvious errors or lackings?

**Comment by josteink** [comment]
Merged and fixed. Reopen if you encounter any issues.
